package io.github.gelassen.manufactory_knowledge_management.repository

import io.github.gelassen.manufactory_knowledge_management.model.Breakdown
import io.github.gelassen.manufactory_knowledge_management.model.Machine
import org.springframework.data.jpa.repository.JpaRepository
import org.springframework.data.repository.CrudRepository
import org.springframework.data.repository.NoRepositoryBean
import org.springframework.data.repository.Repository


//@NoRepositoryBean
interface CustomMachinesRepository {

    fun getAllMachines() : List<Machine> // doesn't follow spring naming convention - doesn't autogenerated
}

interface MachinesRepository : JpaRepository<Machine, Long>, CustomMachinesRepository {

    fun findMachineByBarcode(barcode: String) : Machine? // follow spring naming convention - autogenerated

}

/*
*   Ref. https://docs.spring.io/spring-data/jpa/reference/repositories/definition.html#page-title
* */

@NoRepositoryBean
interface CustomBreakdownsRepository : Repository<Breakdown, Long> {
    fun getBreakdownsByMachine(machine: Machine) : Collection<Breakdown>
}

interface BreakdownsRepository : CrudRepository<Breakdown, Long>, CustomBreakdownsRepository {}
