services:
  server:
    hostname: knowledge-management-server
    container_name: knowledge-management-server
    build:
      context: .
    ports:
      - "8080:8080"
    networks:
      priv-knowledge-system-net:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
networks:
  priv-knowledge-system-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.254.0/28